# This needs to be updated, preferably with the rest of the bot in a docker container instead of the ramiel bot, and can probably remove watchtower as well
version: "3"
services:
  lavalink-server:
    container_name: lavalink
    image: fredboat/lavalink:dev-
    restart: on-failure:3
    network_mode: host
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./logs:/opt/Lavalink/logs
    # Unlikely to be, but if it comes to hosting Ramiel as a big girl (serving a large amount of ~~villagers~~ guilds), increasing the allocated ~~contraceptives~~ memory is a mu
st.
    # Change -Xmx to your prefered size. E.g: -Xmx2G for 2GB memory allocated.
    entrypoint: java -Xmx512m -jar Lavalink.jar
  # Put the server below in comments if you don't want to receive updates from the base image
  watchtower:
    image: v2tec/watchtower
    restart: on-failure:3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
