# This template is for source building docker containers
version: "3"
services:
  lavalink-server:
    container_name: lavalink
    image: fredboat/lavalink:dev-
    restart: on-failure:3
    network_mode: host
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./logs:/opt/Lavalink/logs
    entrypoint: java -Xmx1024m -jar Lavalink.jar
  # Put the server below in comments if you don't want to receive updates from the base image
  watchtower:
    image: v2tec/watchtower
    restart: on-failure:3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
